--Populating meal table
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000000', '1', 'Poisson cru', 'Breakfast', './assets/img/bbq_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000001', '2', 'Dan bauk', 'Lunch', './assets/img/tandoori_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000002', '3', 'Nalca', 'Dinner', './assets/img/fried_fish.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000003', '4', 'Huckabuck', 'Dinner', './assets/img/fish_fillet.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000004', '5', 'Onion Samosa', 'Dinner', './assets/img/fried_fish.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000005', '6', 'Kotlet mielony', 'Breakfast', './assets/img/fried_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000006', '7', 'Sorbetes', 'Dinner', './assets/img/fried_fish.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000007', '8', 'Grilled Cheese', 'Breakfast', './assets/img/fried_chicken.jpg', 1);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000008', '9', 'Chukadon', 'Dinner', './assets/img/bbq_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000009', '10', 'Pavlova', 'Lunch', './assets/img/bbq_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000010', '11', 'Crostini', 'Breakfast', './assets/img/fried_fish.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000011', '12', 'Chukadon', 'Lunch', './assets/img/tandoori_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000012', '13', 'Biryani', 'Lunch', './assets/img/fried_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000013', '14', 'Cheddar', 'Dinner', './assets/img/bbq_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000014', '15', 'Khorkhog', 'Dinner', './assets/img/fried_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000015', '16', 'French meringue', 'Lunch', './assets/img/tandoori_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000016', '17', 'Licke police', 'Dinner', './assets/img/fish_fillet.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000017', '18', 'Eclair', 'Breakfast', './assets/img/tandoori_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000018', '19', 'Misua', 'Lunch', './assets/img/tandoori_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000019', '20', 'Eccles Cake', 'Dinner', './assets/img/fish_fillet.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000020', '21', 'Mala Sauce', 'Breakfast', './assets/img/tandoori_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000021', '22', 'Strozzapreti', 'Dinner', './assets/img/fish_fillet.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000022', '23', 'Miso Soup', 'Lunch', './assets/img/fried_fish.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000023', '24', 'Topoi', 'Breakfast', './assets/img/fried_fish.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000024', '25', 'Guacomole', 'Breakfast', './assets/img/fried_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000025', '26', 'Kouign amann', 'Dinner', './assets/img/fried_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000026', '27', 'Kathi Roll', 'Breakfast', './assets/img/tandoori_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000027', '28', 'Wonton', 'Dinner', './assets/img/bbq_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000028', '29', 'Karengo, Dulse', 'Lunch', './assets/img/tandoori_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000029', '30', 'Zenzai', 'Lunch', './assets/img/tandoori_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000030', '31', 'Bacon and Egg Pie', 'Lunch', './assets/img/fried_fish.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000031', '32', 'Misua', 'Breakfast', './assets/img/fried_fish.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000032', '33', 'Gnocchi', 'Dinner', './assets/img/fish_fillet.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000033', '34', 'Pita Bread', 'Lunch', './assets/img/fish_fillet.jpg', 1);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000034', '35', 'Quesadilla', 'Dinner', './assets/img/fried_fish.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000035', '36', 'Yakiniku', 'Lunch', './assets/img/fried_fish.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000036', '37', 'Bakwan', 'Lunch', './assets/img/bbq_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000037', '38', 'Ramen Burger', 'Dinner', './assets/img/fried_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000038', '39', 'Shashlik', 'Lunch', './assets/img/fried_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000039', '40', 'Ramen Burger', 'Dinner', './assets/img/fried_fish.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000040', '41', 'Pieczarki marynowane', 'Lunch', './assets/img/fried_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000041', '42', 'Quiche', 'Breakfast', './assets/img/fried_chicken.jpg', 1);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000042', '43', 'Mojama', 'Dinner', './assets/img/fish_fillet.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000043', '44', 'Misa', 'Breakfast', './assets/img/tandoori_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000044', '45', 'Maccheroni alla chitarra', 'Dinner', './assets/img/tandoori_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000045', '46', 'Paska skuta', 'Breakfast', './assets/img/fried_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000046', '47', 'Pork Pie', 'Breakfast', './assets/img/tandoori_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000047', '48', 'Canele', 'Lunch', './assets/img/fish_fillet.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000048', '49', 'Kardinalschnitte', 'Dinner', './assets/img/fried_fish.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000049', '50', 'ackee and saltfish', 'Breakfast', './assets/img/fish_fillet.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000050', '51', 'Hummus Beiruti', 'Lunch', './assets/img/bbq_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000051', '52', 'Mac and cheese', 'Lunch', './assets/img/fried_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000052', '53', 'SuchiKimbapOnigiriInjeolmiHoedeopbapChungmu gimbap', 'Breakfast', './assets/img/tandoori_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000053', '54', 'Inasal na manok', 'Lunch', './assets/img/tandoori_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000054', '55', 'Meyer Vintage', 'Breakfast', './assets/img/bbq_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000055', '56', 'Mung Bean Sheets', 'Dinner', './assets/img/fish_fillet.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000056', '57', 'Aloo tikki', 'Dinner', './assets/img/fish_fillet.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000057', '58', 'Laksa', 'Breakfast', './assets/img/fish_fillet.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000058', '59', 'Kotlet schabowy', 'Lunch', './assets/img/bbq_chicken.jpg', 1);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000059', '60', 'Kaiseki', 'Breakfast', './assets/img/fish_fillet.jpg', 3);
