--Populating recipe table
insert into recipe(recipe_name, recipe_description) values ('Poisson cru', 'Into huge hard really agreement pressure.');
insert into recipe(recipe_name, recipe_description) values ('Dan bauk', 'These able sure majority rule.');
insert into recipe(recipe_name, recipe_description) values ('Nalca', 'Already prevent material room room rise.');
insert into recipe(recipe_name, recipe_description) values ('Huckabuck', 'Choice common young likely anyone.');
insert into recipe(recipe_name, recipe_description) values ('Onion Samosa', 'Offer run cover must teacher.');
insert into recipe(recipe_name, recipe_description) values ('Kotlet mielony', 'Detail certain hour system.');
insert into recipe(recipe_name, recipe_description) values ('Sorbetes', 'Bad behind reality information land can baby.');
insert into recipe(recipe_name, recipe_description) values ('Grilled Cheese', 'Smile cold able course ready.');
insert into recipe(recipe_name, recipe_description) values ('Chukadon', 'Easy concern official class marriage.');
insert into recipe(recipe_name, recipe_description) values ('Pavlova', 'Ahead share common alone usually American.');
insert into recipe(recipe_name, recipe_description) values ('Crostini', 'Throughout move between likely sort.');
insert into recipe(recipe_name, recipe_description) values ('Chukadon', 'Into number movement break newspaper visit test.');
insert into recipe(recipe_name, recipe_description) values ('Biryani', 'Former measure hospital network more else item two.');
insert into recipe(recipe_name, recipe_description) values ('Cheddar', 'Major argue short together.');
insert into recipe(recipe_name, recipe_description) values ('Khorkhog', 'National friend audience note approach majority.');
insert into recipe(recipe_name, recipe_description) values ('French meringue', 'Paper part general minute exist soon stop.');
insert into recipe(recipe_name, recipe_description) values ('Licke police', 'Administration provide enough cut however talk.');
insert into recipe(recipe_name, recipe_description) values ('Eclair', 'Same situation smile hospital member recently sit.');
insert into recipe(recipe_name, recipe_description) values ('Misua', 'Let great forward drop movie still discuss.');
insert into recipe(recipe_name, recipe_description) values ('Eccles Cake', 'Change last option already position.');
insert into recipe(recipe_name, recipe_description) values ('Mala Sauce', 'Probably stuff sea word.');
insert into recipe(recipe_name, recipe_description) values ('Strozzapreti', 'Help represent late town receive someone despite.');
insert into recipe(recipe_name, recipe_description) values ('Miso Soup', 'Ground one happy red change.');
insert into recipe(recipe_name, recipe_description) values ('Topoi', 'Effort college game fish year happy manager.');
insert into recipe(recipe_name, recipe_description) values ('Guacomole', 'Art then question business beyond accept red film.');
insert into recipe(recipe_name, recipe_description) values ('Kouign amann', 'Class civil industry young.');
insert into recipe(recipe_name, recipe_description) values ('Kathi Roll', 'World low language total pick sense exactly skill.');
insert into recipe(recipe_name, recipe_description) values ('Wonton', 'Thousand performance mention stock.');
insert into recipe(recipe_name, recipe_description) values ('Karengo, Dulse', 'Two thank human conference husband loss two.');
insert into recipe(recipe_name, recipe_description) values ('Zenzai', 'Bank hope out free open wide feeling kind.');
insert into recipe(recipe_name, recipe_description) values ('Bacon and Egg Pie', 'Stock book forget life.');
insert into recipe(recipe_name, recipe_description) values ('Misua', 'To ever worry weight.');
insert into recipe(recipe_name, recipe_description) values ('Gnocchi', 'Avoid hope building organization we idea.');
insert into recipe(recipe_name, recipe_description) values ('Pita Bread', 'Never drug talk air itself understand short election.');
insert into recipe(recipe_name, recipe_description) values ('Quesadilla', 'Happy purpose eat ago authority plant.');
insert into recipe(recipe_name, recipe_description) values ('Yakiniku', 'Debate however ready across both party.');
insert into recipe(recipe_name, recipe_description) values ('Bakwan', 'Model west clearly machine sport together from.');
insert into recipe(recipe_name, recipe_description) values ('Ramen Burger', 'No fish west hope movie expert lay.');
insert into recipe(recipe_name, recipe_description) values ('Shashlik', 'Face human if especially choice Mr.');
insert into recipe(recipe_name, recipe_description) values ('Ramen Burger', 'Magazine long food thousand happy race realize.');
insert into recipe(recipe_name, recipe_description) values ('Pieczarki marynowane', 'Simply arrive raise.');
insert into recipe(recipe_name, recipe_description) values ('Quiche', 'Soon cut idea sing sit red.');
insert into recipe(recipe_name, recipe_description) values ('Mojama', 'Create hot course what common.');
insert into recipe(recipe_name, recipe_description) values ('Misa', 'Tv protect serious include under play such.');
insert into recipe(recipe_name, recipe_description) values ('Maccheroni alla chitarra', 'Data charge to accept sea break agency.');
insert into recipe(recipe_name, recipe_description) values ('Paska skuta', 'Dream not western probably family shoulder executive.');
insert into recipe(recipe_name, recipe_description) values ('Pork Pie', 'Out guess western scientist.');
insert into recipe(recipe_name, recipe_description) values ('Canele', 'Agreement simply service than final one account rise.');
insert into recipe(recipe_name, recipe_description) values ('Kardinalschnitte', 'Quickly yet century tend quite network.');
insert into recipe(recipe_name, recipe_description) values ('ackee and saltfish', 'Yourself soldier affect parent order watch final.');
insert into recipe(recipe_name, recipe_description) values ('Hummus Beiruti', 'Each house success throw.');
insert into recipe(recipe_name, recipe_description) values ('Mac and cheese', 'Attack month choice why partner six federal.');
insert into recipe(recipe_name, recipe_description) values ('SuchiKimbapOnigiriInjeolmiHoedeopbapChungmu gimbap', 'Consider else central offer ahead.');
insert into recipe(recipe_name, recipe_description) values ('Inasal na manok', 'Represent up free skin choose head.');
insert into recipe(recipe_name, recipe_description) values ('Meyer Vintage', 'Space decade myself land matter.');
insert into recipe(recipe_name, recipe_description) values ('Mung Bean Sheets', 'Say medical write easy laugh next positive.');
insert into recipe(recipe_name, recipe_description) values ('Aloo tikki', 'Here building food situation writer.');
insert into recipe(recipe_name, recipe_description) values ('Laksa', 'Hospital mouth yes personal social.');
insert into recipe(recipe_name, recipe_description) values ('Kotlet schabowy', 'Knowledge focus color its.');
insert into recipe(recipe_name, recipe_description) values ('Kaiseki', 'Evening debate history glass floor.');
