--Populating meal table
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000000', '1', 'Kuku sib zamini', 'Breakfast', './assets/img/fried_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000001', '2', 'Fatanyeros', 'Lunch', './assets/img/tandoori_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000002', '3', 'Fofos de arroz', 'Dinner', './assets/img/fish_fillet.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000003', '4', 'Eclair', 'Dinner', './assets/img/bbq_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000004', '5', 'Cronut', 'Lunch', './assets/img/fried_fish.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000005', '6', 'Shish kebab', 'Lunch', './assets/img/fried_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000006', '7', 'Tagliatelle al ragu alla Bolognese', 'Lunch', './assets/img/tandoori_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000007', '8', 'Borrachuelos', 'Breakfast', './assets/img/bbq_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000008', '9', 'Sanuki', 'Dinner', './assets/img/fish_fillet.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000009', '10', 'Doenjang', 'Dinner', './assets/img/fried_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000010', '11', 'Feta', 'Lunch', './assets/img/fried_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000011', '12', 'Mkhabez', 'Breakfast', './assets/img/fried_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000012', '13', 'Crostini', 'Lunch', './assets/img/bbq_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000013', '14', 'Aush', 'Dinner', './assets/img/fried_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000014', '15', 'Teppanyaki', 'Breakfast', './assets/img/fried_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000015', '16', 'Risotto ai funghi', 'Dinner', './assets/img/bbq_chicken.jpg', 1);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000016', '17', 'Cai', 'Breakfast', './assets/img/tandoori_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000017', '18', 'Spaghetti al guanciale', 'Breakfast', './assets/img/fried_fish.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000018', '19', 'Eclair', 'Dinner', './assets/img/bbq_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000019', '20', 'Pommes frites', 'Dinner', './assets/img/fried_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000020', '21', 'Smultring', 'Breakfast', './assets/img/fried_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000021', '22', 'Guacomole', 'Dinner', './assets/img/fish_fillet.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000022', '23', 'Tiramisu', 'Dinner', './assets/img/fish_fillet.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000023', '24', 'Shakoy', 'Dinner', './assets/img/fried_fish.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000024', '25', 'Cha siu bao ', 'Dinner', './assets/img/bbq_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000025', '26', 'Garnacha', 'Dinner', './assets/img/bbq_chicken.jpg', 1);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000026', '27', 'Har gow', 'Breakfast', './assets/img/bbq_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000027', '28', 'Cheesecake Brownies', 'Dinner', './assets/img/fried_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000028', '29', 'Entomatadas', 'Dinner', './assets/img/tandoori_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000029', '30', 'Australian Barbecue', 'Lunch', './assets/img/fish_fillet.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000030', '31', 'Granita al limone', 'Dinner', './assets/img/tandoori_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000031', '32', 'Pao cai', 'Lunch', './assets/img/fried_fish.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000032', '33', 'Nudelsuppe', 'Dinner', './assets/img/fried_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000033', '34', 'Cheesecake Brownies', 'Dinner', './assets/img/fried_fish.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000034', '35', 'Pane carasau', 'Lunch', './assets/img/fish_fillet.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000035', '36', 'Kathi Roll', 'Breakfast', './assets/img/fried_fish.jpg', 1);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000036', '37', 'Pita Bread', 'Dinner', './assets/img/bbq_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000037', '38', 'Macarons', 'Dinner', './assets/img/fish_fillet.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000038', '39', 'Bol', 'Lunch', './assets/img/fried_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000039', '40', 'Alfajor', 'Dinner', './assets/img/fried_fish.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000040', '41', 'Hiyamugi', 'Breakfast', './assets/img/fried_fish.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000041', '42', 'Kamameshi', 'Lunch', './assets/img/fried_fish.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000042', '43', 'Maqluba Mathlotha', 'Lunch', './assets/img/bbq_chicken.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000043', '44', 'Dolcelatte', 'Breakfast', './assets/img/fried_fish.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000044', '45', 'Mei gan cai', 'Breakfast', './assets/img/bbq_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000045', '46', 'Tagliatelle al ragu alla Bolognese', 'Breakfast', './assets/img/fish_fillet.jpg', 1);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000046', '47', 'Mung Bean Sheets', 'Lunch', './assets/img/fried_fish.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000047', '48', 'Asado', 'Lunch', './assets/img/tandoori_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000048', '49', 'Mojama', 'Breakfast', './assets/img/fried_fish.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000049', '50', 'Gnocchi', 'Breakfast', './assets/img/tandoori_chicken.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000050', '51', 'Submarine Sandwich', 'Breakfast', './assets/img/fried_fish.jpg', 3);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000051', '52', 'Tiramisu', 'Breakfast', './assets/img/bbq_chicken.jpg', 5);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000052', '53', 'Cha siu bao', 'Lunch', './assets/img/bbq_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000053', '54', 'Onigiri', 'Dinner', './assets/img/tandoori_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000054', '55', 'Chili Burger', 'Breakfast', './assets/img/tandoori_chicken.jpg', 1);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000055', '56', 'Pain de mie', 'Lunch', './assets/img/fried_fish.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000056', '57', 'Daheen', 'Dinner', './assets/img/fish_fillet.jpg', 2);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000057', '58', 'Migas, Riganada', 'Lunch', './assets/img/fish_fillet.jpg', 1);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000058', '59', 'Rouille', 'Lunch', './assets/img/tandoori_chicken.jpg', 4);
insert into meal(meal_id, recipe_id, meal_name, meal_type, meal_image, servings) values ('M000059', '60', 'Dasik', 'Lunch', './assets/img/fried_chicken.jpg', 4);
