--Populating recipe table
insert into recipe(recipe_name, recipe_description) values ('Kuku sib zamini', 'We choose energy hair pass.');
insert into recipe(recipe_name, recipe_description) values ('Fatanyeros', 'Thousand decide speak economic game bed accept.');
insert into recipe(recipe_name, recipe_description) values ('Fofos de arroz', 'Environmental statement thought painting others next animal.');
insert into recipe(recipe_name, recipe_description) values ('Eclair', 'Budget especially shake nature until once would.');
insert into recipe(recipe_name, recipe_description) values ('Cronut', 'You some easy their.');
insert into recipe(recipe_name, recipe_description) values ('Shish kebab', 'Range man end alone example loss affect give.');
insert into recipe(recipe_name, recipe_description) values ('Tagliatelle al ragu alla Bolognese', 'Rest audience ready site.');
insert into recipe(recipe_name, recipe_description) values ('Borrachuelos', 'Wrong while short such.');
insert into recipe(recipe_name, recipe_description) values ('Sanuki', 'War safe like note cost.');
insert into recipe(recipe_name, recipe_description) values ('Doenjang', 'Few whom firm require stuff experience bank.');
insert into recipe(recipe_name, recipe_description) values ('Feta', 'Edge religious produce.');
insert into recipe(recipe_name, recipe_description) values ('Mkhabez', 'Mr together bag look case Republican rate.');
insert into recipe(recipe_name, recipe_description) values ('Crostini', 'Building spring ball firm dark green.');
insert into recipe(recipe_name, recipe_description) values ('Aush', 'Enough cultural improve I part agent.');
insert into recipe(recipe_name, recipe_description) values ('Teppanyaki', 'Than certain military eight.');
insert into recipe(recipe_name, recipe_description) values ('Risotto ai funghi', 'Standard role cut model common.');
insert into recipe(recipe_name, recipe_description) values ('Cai', 'Interesting dog around effect production individual.');
insert into recipe(recipe_name, recipe_description) values ('Spaghetti al guanciale', 'Election hear war forward someone specific I.');
insert into recipe(recipe_name, recipe_description) values ('Eclair', 'Song everybody threat himself go there hotel.');
insert into recipe(recipe_name, recipe_description) values ('Pommes frites', 'Go tonight support attorney specific behavior old actually.');
insert into recipe(recipe_name, recipe_description) values ('Smultring', 'Safe while again suggest.');
insert into recipe(recipe_name, recipe_description) values ('Guacomole', 'Cell drop maybe possible end.');
insert into recipe(recipe_name, recipe_description) values ('Tiramisu', 'This industry section garden responsibility picture.');
insert into recipe(recipe_name, recipe_description) values ('Shakoy', 'Health detail west keep occur in hour.');
insert into recipe(recipe_name, recipe_description) values ('Cha siu bao ', 'Real above exactly minute.');
insert into recipe(recipe_name, recipe_description) values ('Garnacha', 'Professional analysis economy whatever believe.');
insert into recipe(recipe_name, recipe_description) values ('Har gow', 'Religious turn risk traditional lead magazine.');
insert into recipe(recipe_name, recipe_description) values ('Cheesecake Brownies', 'Company soldier should rule cover model impact.');
insert into recipe(recipe_name, recipe_description) values ('Entomatadas', 'Listen you staff worry moment figure happy.');
insert into recipe(recipe_name, recipe_description) values ('Australian Barbecue', 'Also night matter course stock suggest.');
insert into recipe(recipe_name, recipe_description) values ('Granita al limone', 'Everybody old deep left big coach whom.');
insert into recipe(recipe_name, recipe_description) values ('Pao cai', 'Weight company cell theory mouth big.');
insert into recipe(recipe_name, recipe_description) values ('Nudelsuppe', 'Simply gun green business air until financial.');
insert into recipe(recipe_name, recipe_description) values ('Cheesecake Brownies', 'Community trouble card fall price along quite.');
insert into recipe(recipe_name, recipe_description) values ('Pane carasau', 'Scientist community star after.');
insert into recipe(recipe_name, recipe_description) values ('Kathi Roll', 'All like school write prove.');
insert into recipe(recipe_name, recipe_description) values ('Pita Bread', 'Upon herself but woman often it goal.');
insert into recipe(recipe_name, recipe_description) values ('Macarons', 'Draw these later hope fear operation.');
insert into recipe(recipe_name, recipe_description) values ('Bol', 'Finally order response hope offer.');
insert into recipe(recipe_name, recipe_description) values ('Alfajor', 'Receive company suffer physical four eat.');
insert into recipe(recipe_name, recipe_description) values ('Hiyamugi', 'Receive life manage.');
insert into recipe(recipe_name, recipe_description) values ('Kamameshi', 'Hot fine end marriage move authority.');
insert into recipe(recipe_name, recipe_description) values ('Maqluba Mathlotha', 'Use history season business prepare.');
insert into recipe(recipe_name, recipe_description) values ('Dolcelatte', 'Majority issue quality thus.');
insert into recipe(recipe_name, recipe_description) values ('Mei gan cai', 'Road practice develop information night list figure worry.');
insert into recipe(recipe_name, recipe_description) values ('Tagliatelle al ragu alla Bolognese', 'Attention officer campaign person purpose last.');
insert into recipe(recipe_name, recipe_description) values ('Mung Bean Sheets', 'Stage scene whom fire.');
insert into recipe(recipe_name, recipe_description) values ('Asado', 'Author myself might drug prove everybody activity.');
insert into recipe(recipe_name, recipe_description) values ('Mojama', 'Coach institution training prevent fall finish.');
insert into recipe(recipe_name, recipe_description) values ('Gnocchi', 'Exactly whole myself artist window push.');
insert into recipe(recipe_name, recipe_description) values ('Submarine Sandwich', 'Partner protect involve standard design value measure.');
insert into recipe(recipe_name, recipe_description) values ('Tiramisu', 'Company defense interview scene news last pass fish.');
insert into recipe(recipe_name, recipe_description) values ('Cha siu bao', 'Travel be it price.');
insert into recipe(recipe_name, recipe_description) values ('Onigiri', 'Thank right news rest put woman marriage process.');
insert into recipe(recipe_name, recipe_description) values ('Chili Burger', 'And within such property.');
insert into recipe(recipe_name, recipe_description) values ('Pain de mie', 'If common set behavior everybody.');
insert into recipe(recipe_name, recipe_description) values ('Daheen', 'Should kid another.');
insert into recipe(recipe_name, recipe_description) values ('Migas, Riganada', 'Prevent machine ever risk base.');
insert into recipe(recipe_name, recipe_description) values ('Rouille', 'Blood although million card both most the.');
insert into recipe(recipe_name, recipe_description) values ('Dasik', 'Say mention skill first hair.');
